export const getSlippageToleranceDescription = (): string => {
  return (
    'Slippage Tolerance is the pricing difference between the price at the confirmation ' +
    // eslint-disable-next-line max-len
    'time and the actual price of the transaction users are willing to accept when swapping on AMMs. ' +
    'Slippage tolerance is set as a percentage of the total swap value.'
  );
};

export const getSwapPoolDescription = (): string => {
  return (
    'It is important to reiterate that a Pool is just a smart contract, operated by ' +
    'users calling functions on it. Swapping tokens is calling swap on a Pool contract ' +
    'instance, while providing liquidity is calling deposit .'
  );
};

export const getMinimumReceivedDescription = (): string => {
  return (
    'Minimum received is the minimum number of tokens in which the swap takes place, ' +
    'which the user will receive, minus the slippage tolerance.'
  );
};

export const getPriceImpactDescription = (): string => {
  return (
    'Price impact is an expression used to describe the correlation between an ' +
    'incoming order and the change in the price of the asset involved caused by the trade.'
  );
};

export const getEcoContributionDescription = (): string => {
  return (
    'The eco-contribution also called eco-participation is the annual financial compensation ' +
    'paid by a company (producer, distributor, or importer) to a certified eco-organism ' +
    '(ex. CITEO, born of the fusion of Eco-Emballages with Ecofolio, Eco-Systèmes) for the ' +
    'management of the disposal of waste generated by its activities pursuant to an Extended ' +
    'Producer Responsibility sector (EPR).'
  );
};

export const getExpiresInDescription = (seconds: number): string => {
  return (
    `Displayed data will be auto-refresh after ${50 - seconds} seconds. ` +
    'Click the update button to update manually.'
  );
};
